#!c:\users\dell\documents\udemy-django\rathankumar\greatkart2\rathankumar\greatkart\scripts\python.exe

import sys

if __name__ == "__main__":
    from EB.builder.eb_main import main
    sys.exit(main(sys.argv))
