#!C:\Users\Dell\Documents\Udemy-Django\RathanKumar\GreatKart2\RathanKumar\GreatKart\Scripts\python.exe

import sys

if __name__ == "__main__":
    from EB.builder.eb_main import main
    sys.exit(main(sys.argv))
